<a href="https://colab.research.google.com/github/thinkdeepai/reinforcement-learning-training/blob/master/QLearning_Taxi_Driver.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import gym
import random
import numpy as np
import time, pickle, os

In [0]:
env = gym.make('Taxi-v3')
env.reset()
epsilon = 0.9
total_episodes = 10000
max_steps = 100
lr_rate = 0.81
gamma = 0.96


In [0]:
def choose_action(state):
    action=0
    if np.random.uniform(0, 1) < epsilon:
        action = env.action_space.sample()
    else:
        action = np.argmax(Q[state, :])
    return action

def learn(state, state2, reward, action):
    old_value = Q[state, action]
    learned_value = reward + gamma * np.max(Q[state2, :])
    Q[state, action] = (1 - lr_rate) * old_value +  lr_rate * learned_value

In [5]:
Q = np.zeros((env.observation_space.n, env.action_space.n))

# Start
for episode in range(total_episodes):
    state = env.reset()
    t = 0
    while t < max_steps:
        #env.render()
        action = choose_action(state)  
        state2, reward, done, info = env.step(action)  
        learn(state, state2, reward, action)
        state = state2
        t += 1
        if done:
            break

print(Q)




[[ 0.          0.          0.          0.          0.          0.        ]
 [ 3.72076987  4.91746862  3.72076987  4.91746862  6.16402981 -4.08253138]
 [ 8.81513651 10.22410054  8.81513651 10.22410054 11.69177139  1.22410054]
 ...
 [11.69177139 13.2205952  11.69177139 10.22410054  2.69177139  2.69177139]
 [ 6.16402981  7.46253105  6.16402981  7.46253105 -2.83597019 -2.83597019]
 [16.472      14.81312    16.472      18.2         7.472       7.472     ]]


In [0]:
np.save("qtable-taxi", Q)

In [0]:
#Q = np.load("qtable-taxi.npy")

In [0]:
"""Evaluate agent's performance after Q-learning"""
def evaluate(random_mode=False):
  total_epochs, total_rewards = 0, 0

  for _ in range(total_episodes):
      state = env.reset()
      epochs, reward = 0, 0
      done = False
      while not done:
          if random_mode:
            action = env.action_space.sample()
          else:
            action = np.argmax(Q[state, :])
          state, reward, done, info = env.step(action)

          epochs += 1

      total_rewards += reward
      total_epochs += epochs

  print(f"Results after {total_episodes} episodes:")
  print(f"Average timesteps per episode: {total_epochs / total_episodes}")
  print(f"Average rewards per episode: {total_rewards / total_episodes}")

In [23]:
evaluate(random_mode=True)

Results after 10000 episodes:
Average timesteps per episode: 196.5861
Average rewards per episode: -2.8489


In [24]:
evaluate(random_mode=False)

Results after 10000 episodes:
Average timesteps per episode: 13.083
Average rewards per episode: 20.0
