<a href="https://colab.research.google.com/github/thinkdeepai/reinforcement-learning-training/blob/master/QLearning_Frozen_Lake.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import gym
import random
import numpy as np
import time, pickle, os

In [0]:
env = gym.make('FrozenLake-v0')
env.reset()
epsilon = 0.9
total_episodes = 10000
max_steps = 100
lr_rate = 0.81
gamma = 0.96


In [0]:
def choose_action(state):
    action=0
    if np.random.uniform(0, 1) < epsilon:
        action = env.action_space.sample()
    else:
        action = np.argmax(Q[state, :])
    return action

def old_learn(state, state2, reward, action):
    predict = Q[state, action]
    target = reward + gamma * np.max(Q[state2, :])
    Q[state, action] = Q[state, action] + lr_rate * (target - predict)

def learn(state, state2, reward, action):
    old_value = Q[state, action]
    learned_value = reward + gamma * np.max(Q[state2, :])
    Q[state, action] = (1 - lr_rate) * old_value +  lr_rate * learned_value

In [46]:
Q = np.zeros((env.observation_space.n, env.action_space.n))

# Start
for episode in range(total_episodes):
    state = env.reset()
    t = 0
    while t < max_steps:
        #env.render()
        action = choose_action(state)  
        state2, reward, done, info = env.step(action)  
        learn(state, state2, reward, action)
        state = state2
        t += 1
        if done:
            break

print(Q)


[[7.17864968e-01 7.31080208e-01 6.18929503e-01 6.25141654e-01]
 [7.11877076e-04 3.61445682e-03 4.06002161e-01 5.38043281e-01]
 [5.62042016e-01 5.24711143e-01 5.37354430e-01 5.70266846e-01]
 [9.86366456e-02 5.50535395e-01 4.92386530e-01 5.08238613e-01]
 [7.70128692e-01 5.99771748e-01 2.31661095e-02 7.32323506e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [4.64365203e-01 3.42010051e-05 2.61899401e-02 1.09245364e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [6.74934506e-01 7.64780744e-01 7.55818492e-01 8.33349969e-01]
 [2.81449618e-02 8.14045854e-01 7.50238882e-01 1.33175223e-01]
 [7.67538481e-01 7.80295329e-01 7.98821147e-01 1.22338969e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [6.83791307e-01 8.43564899e-01 7.63645000e-01 9.30289797e-01]
 [9.31595580e-01 9.99634805e-01 9.99331633e-01 7.82640552e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.000000