<a href="https://colab.research.google.com/github/thinkdeepai/reinforcement-learning-training/blob/master/QLearning_Frozen_Lake.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import gym
import random
import numpy as np
import time, pickle, os

In [0]:
env = gym.make('FrozenLake8x8-v0')
env.reset()
epsilon = 0.9
total_episodes = 10000
max_steps = 100
lr_rate = 0.81
gamma = 0.96


In [0]:
def choose_action(state):
    action=0
    if np.random.uniform(0, 1) < epsilon:
        action = env.action_space.sample()
    else:
        action = np.argmax(Q[state, :])
    return action

def old_learn(state, state2, reward, action):
    predict = Q[state, action]
    target = reward + gamma * np.max(Q[state2, :])
    Q[state, action] = Q[state, action] + lr_rate * (target - predict)

def learn(state, state2, reward, action):
    old_value = Q[state, action]
    learned_value = reward + gamma * np.max(Q[state2, :])
    Q[state, action] = (1 - lr_rate) * old_value +  lr_rate * learned_value

In [51]:
Q = np.zeros((env.observation_space.n, env.action_space.n))

# Start
for episode in range(total_episodes):
    state = env.reset()
    t = 0
    while t < max_steps:
        #env.render()
        action = choose_action(state)  
        state2, reward, done, info = env.step(action)  
        learn(state, state2, reward, action)
        state = state2
        t += 1
        if done:
            break

print(Q)


[[4.01734871e-01 3.96545486e-01 3.97943665e-01 3.98884776e-01]
 [4.04834766e-01 3.96815318e-01 4.44070841e-01 4.02630992e-01]
 [4.11269571e-01 4.67206771e-01 4.44343147e-01 4.46723826e-01]
 [4.86605893e-01 5.19676838e-01 4.80513368e-01 4.73887811e-01]
 [5.07350967e-01 5.57588587e-01 5.17932810e-01 4.89098710e-01]
 [5.25576448e-01 5.27945166e-01 5.59517726e-01 5.42111269e-01]
 [5.65182770e-01 5.41692033e-01 5.68451891e-01 5.54124978e-01]
 [5.85574058e-01 5.88870124e-01 5.88623355e-01 5.64332856e-01]
 [3.85325215e-01 4.18519448e-01 4.00100461e-01 4.01611529e-01]
 [3.98582866e-01 3.97131688e-01 4.36011330e-01 4.37998943e-01]
 [4.06516929e-01 4.73560357e-01 4.28418073e-01 4.23093517e-01]
 [1.50652537e-02 5.07114723e-01 7.07203014e-02 4.72669219e-01]
 [5.04593251e-01 4.79008765e-01 5.09577351e-01 5.24066428e-01]
 [5.20463633e-01 5.29290560e-01 5.24900056e-01 5.80113289e-01]
 [6.26777257e-01 5.63412022e-01 5.97138391e-01 5.96801287e-01]
 [6.46555911e-01 5.80666337e-01 5.70135470e-01 5.765296