<a href="https://colab.research.google.com/github/thinkdeepai/reinforcement-learning-training/blob/master/QLearning_Frozen_Lake.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import gym
import random
import numpy as np
import time, pickle, os

In [0]:
env = gym.make('FrozenLake8x8-v0')
env.reset()
epsilon = 0.9
total_episodes = 10000
max_steps = 100
lr_rate = 0.81
gamma = 0.96


In [0]:
def choose_action(state):
    action=0
    if np.random.uniform(0, 1) < epsilon:
        action = env.action_space.sample()
    else:
        action = np.argmax(Q[state, :])
    return action

def learn(state, state2, reward, action):
    old_value = Q[state, action]
    learned_value = reward + gamma * np.max(Q[state2, :])
    Q[state, action] = (1 - lr_rate) * old_value +  lr_rate * learned_value

In [56]:
Q = np.zeros((env.observation_space.n, env.action_space.n))

# Start
for episode in range(total_episodes):
    state = env.reset()
    t = 0
    while t < max_steps:
        #env.render()
        action = choose_action(state)  
        state2, reward, done, info = env.step(action)  
        learn(state, state2, reward, action)
        state = state2
        t += 1
        if done:
            break

print(Q)




[[4.10163191e-01 4.12956050e-01 4.10628555e-01 4.46119664e-01]
 [4.23884541e-01 4.82630602e-01 4.41168903e-01 4.29746980e-01]
 [4.98895842e-01 5.04954689e-01 5.04880869e-01 4.95840448e-01]
 [5.34030038e-01 5.03527036e-01 5.03505184e-01 5.14666937e-01]
 [5.14324218e-01 5.60441446e-01 5.55636196e-01 5.58567984e-01]
 [5.48250836e-01 5.80095925e-01 5.61691970e-01 5.77379801e-01]
 [5.79519254e-01 5.70458075e-01 5.88356628e-01 5.74410376e-01]
 [6.02391546e-01 5.89187484e-01 5.76978595e-01 5.84700369e-01]
 [4.07889925e-01 4.12212268e-01 4.27249358e-01 4.35037178e-01]
 [4.20399553e-01 4.54769874e-01 4.43170447e-01 4.56892842e-01]
 [4.78177857e-01 4.91074428e-01 4.89158688e-01 4.91054594e-01]
 [1.82234259e-02 5.08444080e-01 8.34226554e-02 5.16127365e-01]
 [5.44952667e-01 6.03109335e-01 5.93935556e-01 5.36769779e-01]
 [6.29386097e-01 5.88755227e-01 5.77435303e-01 5.78890036e-01]
 [5.84101059e-01 6.60635524e-01 6.23356847e-01 6.16421449e-01]
 [6.25941114e-01 6.39115124e-01 5.89912249e-01 6.297663

In [0]:
np.save("qtable", Q)

In [0]:
Q = np.load("qtable.npy")

In [0]:
"""Evaluate agent's performance after Q-learning"""
def evaluate():
  total_epochs, total_penalties = 0, 0

  for _ in range(total_episodes):
      state = env.reset()
      epochs, penalties, reward = 0, 0, 0
      
      done = False
      
      while not done:
          action = np.argmax(Q[state, :])
          state, reward, done, info = env.step(action)

          if reward < 0:
              penalties += 1

          epochs += 1

      total_penalties += penalties
      total_epochs += epochs

  print(f"Results after {total_episodes} episodes:")
  print(f"Average timesteps per episode: {total_epochs / total_episodes}")
  print(f"Average penalties per episode: {total_penalties / total_episodes}")

In [77]:
evaluate()

Results after 10000 episodes:
Average timesteps per episode: 47.4936
Average penalties per episode: 0.0
